- hosts: web
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
    - name: Iniciar servicio Apache
      service:
        name: apache2
        state: started
    - name: Copiar archivos HTML
      copy:
        src: index.html
        dest: /var/www/html/index.html
